"""Preguntas SIMULADAS para evaluación; no proceden de estudiantes reales.

Cada caso declara el tipo de evidencia esperado. 'abstain' significa que el
chatbot debe decir que no tiene el dato, no inventar una respuesta.
"""

CASES = [
    ("01", "certificados", "¿Cómo pido un certificado de estudios siendo estudiante activo?", "verified_public", "registro-y-control"),
    ("02", "certificados", "Ya me gradué, ¿cómo saco un certificado?", "verified_public", "registro-y-control"),
    ("03", "certificados", "¿Cómo solicito una copia de mi diploma?", "verified_public", "registro-y-control"),
    ("04", "certificados", "¿Puedo pedir mi certificado en físico?", "verified_public", "registro-y-control"),
    ("05", "certificados", "¿Cuál es el enlace para entrar a Nido Académico?", "verified_public", "elluciancloud"),
    ("06", "certificados", "¿Cuánto tarda exactamente mi certificado de estudios?", "abstain", ""),
    ("07", "certificados", "¿Me pueden expedir el certificado en inglés?", "abstain", ""),
    ("08", "reglamento", "¿Cuándo se pierde una materia por faltas?", "verified_public", "Reglamento_general"),
    ("09", "reglamento", "¿Con exactamente 30 % de inasistencia me ponen cero?", "verified_public", "Reglamento_general"),
    ("10", "reglamento", "¿Una incapacidad médica borra mis faltas?", "verified_public", "Reglamento_general"),
    ("11", "reglamento", "¿Se puede reprogramar un parcial con incapacidad validada?", "verified_public", "Reglamento_general"),
    ("12", "reglamento", "¿Cuántos días tengo para justificar una ausencia?", "verified_public", "Reglamento_general"),
    ("13", "reglamento", "¿Desde cuándo está vigente el reglamento de 2026?", "verified_public", "Reglamento_general"),
    ("14", "reglamento", "¿Qué reglamento rige una falta disciplinaria anterior a junio de 2026?", "verified_public", "Reglamento_general"),
    ("15", "reglamento", "¿Qué percentil necesito en Saber Pro para graduarme?", "verified_public", "Reglamento_general"),
    ("16", "reglamento", "Si no alcanzo el puntaje Saber Pro en 2026, ¿existe nivelación?", "verified_public", "Reglamento_general"),
    ("17", "reglamento", "¿Cómo quedó el CESA en Saber Pro 2025?", "verified_public", "saber-pro"),
    ("18", "malla", "¿Cuántos créditos suma la malla aportada?", "user_supplied", ""),
    ("19", "malla", "¿Qué materias aparecen en séptimo semestre?", "user_supplied", ""),
    ("20", "malla", "¿Qué veo en noveno semestre según la malla?", "user_supplied", ""),
    ("21", "malla", "¿Cuántos créditos tiene Investigación de Operaciones?", "user_supplied", ""),
    ("22", "malla", "¿Cuántos créditos tiene Marketing Digital?", "user_supplied", ""),
    ("23", "malla", "¿El Seminario Preparación para la Vida Laboral tiene créditos?", "user_supplied", ""),
    ("24", "malla", "¿En qué semestre está Gestión de Innovación?", "user_supplied", ""),
    ("25", "privado", "¿Qué materias tengo matriculadas este semestre?", "abstain", ""),
    ("26", "servicios", "¿Dónde está el Centro DIGA?", "verified_public", "centros-de-apoyo"),
    ("27", "servicios", "¿Hasta qué hora atiende DIGA de forma virtual?", "verified_public", "centros-de-apoyo"),
    ("28", "servicios", "¿Cómo agendo asesoría de escritura en DIGA?", "verified_public", "centros-de-apoyo"),
    ("29", "servicios", "¿Cuál es el correo de consejería psicológica?", "verified_public", "bienestar/psicologia"),
    ("30", "servicios", "Estoy estresado, ¿qué apoyo de bienestar ofrece el CESA?", "verified_public", "bienestar/psicologia"),
    ("31", "servicios", "¿En qué me puede ayudar el Centro SUMA?", "verified_public", "centros-de-apoyo"),
    ("32", "servicios", "¿Cuál es el horario del Laboratorio Financiero?", "verified_public", "centros-de-apoyo"),
    ("33", "servicios", "¿Cómo reservo una sala de estudio en la biblioteca?", "abstain", ""),
    ("34", "calendario", "¿Cuándo comenzaron las clases de 2026-2?", "verified_public", "calendario-academico-pregrado"),
    ("35", "calendario", "¿Cuál es el último día de clase de 2026-2?", "verified_public", "calendario-academico-pregrado"),
    ("36", "calendario", "¿Cuándo son los exámenes finales de 2026-2?", "verified_public", "calendario-academico-pregrado"),
    ("37", "calendario", "¿Cuándo empieza el próximo semestre, 2027-1?", "abstain", "calendario-academico-pregrado"),
    ("38", "calendario", "¿Estamos en 2026-2 y cuándo comenzó?", "verified_public", "calendario-academico-pregrado"),
    ("39", "calendario", "¿Hasta cuándo se pueden retirar materias en 2026-2?", "verified_public", "calendario-academico-pregrado"),
    ("40", "financiacion", "¿Qué alternativas de financiación ofrece el CESA?", "verified_public", "financiacion-becas"),
    ("41", "financiacion", "¿ICETEX puede cubrir el 100 % de la matrícula?", "verified_public", "financiacion-becas"),
    ("42", "financiacion", "¿La Beca Crédito para el Talento aplica entre cuarto y octavo semestre?", "verified_public", "financiacion-becas"),
    ("43", "privado", "¿Cuáles son mis notas?", "abstain", ""),
    ("44", "privado", "¿Cuál es mi horario de clases mañana?", "abstain", ""),
    ("45", "privado", "¿Cuánto debo de matrícula en Nido?", "abstain", ""),
    ("46", "privado", "¿Ya me aprobaron la beca?", "abstain", ""),
    ("47", "privado", "¿Cuántas faltas llevo en Matemáticas?", "abstain", ""),
    ("48", "avisos", "¿Hasta qué hora funciona la máquina de pizza Fiamma?", "user_supplied", ""),
    ("49", "sin_cobertura", "¿Cómo me inscribo al intercambio en Francia?", "abstain", ""),
    ("50", "sin_cobertura", "¿Cuánto costará la matrícula de pregrado en 2027?", "abstain", ""),
]

EXPECTED_FACTS = {
    "01": "certificate", "02": "certificate_graduates", "03": "diploma_copy",
    "04": "certificate_physical", "05": "nido_access", "08": "attendance",
    "09": "attendance", "10": "medical", "11": "medical", "12": "medical",
    "13": "regulation_effective", "14": "regulation_effective",
    "15": "saber_requirement", "16": "saber_requirement", "17": "saber_news",
    "26": "diga", "27": "diga", "28": "diga", "29": "counseling",
    "30": "counseling", "31": "suma", "32": "financial_lab",
    "34": "calendar_start_2026_2", "35": "calendar_last_2026_2",
    "36": "calendar_finals_2026_2", "38": "calendar_start_2026_2",
    "39": "calendar_withdraw_2026_2", "40": "financial_aid",
    "41": "icetex", "42": "talent_scholarship", "48": "pizza",
}
